# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 05:18
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name=b'Slug')),
                ('date', models.DateField(auto_now_add=True, verbose_name=b'Date')),
                ('content', ckeditor.fields.RichTextField(verbose_name=b'Content')),
            ],
            options={
                'ordering': ['-created_on', '-updated_on'],
                'db_table': 'topics',
            },
        ),
    ]
