# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 21:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('comment', models.TextField(max_length=4000, verbose_name=b'Comment')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name=b'Updated on')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name=b'Name')),
                ('slug', models.SlugField(unique=True, verbose_name=b'Slug')),
                ('content', models.TextField(verbose_name=b'Content')),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.Topic'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
