# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 22:43
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['created_on', 'updated_on']},
        ),
        migrations.AddField(
            model_name='topic',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name=b'Content'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='slug',
            field=models.SlugField(editable=False, unique=True, verbose_name=b'Slug'),
        ),
    ]
