# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 01:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_auto_20170908_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created_on', '-updated_on']},
        ),
    ]
