# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='place',
            field=models.CharField(default=None, max_length=255, verbose_name=b'Place'),
            preserve_default=False,
        ),
    ]
