# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0002_auto_20170916_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='link',
        ),
    ]
