# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0002_emergency_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Need',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, help_text=b'Latitude', max_digits=9, null=True, verbose_name=b'Lat')),
                ('long', models.DecimalField(blank=True, decimal_places=6, help_text=b'Longitude', max_digits=9, null=True, verbose_name=b'Long')),
                ('need_id', models.CharField(max_length=255, verbose_name=b'Need id')),
                ('need', models.TextField(verbose_name=b'Need')),
                ('link', models.CharField(max_length=255, verbose_name=b'Link')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('time', models.CharField(max_length=75, verbose_name=b'Time')),
                ('contact', models.CharField(max_length=255, verbose_name=b'Contact')),
                ('location', models.CharField(max_length=255, verbose_name=b'Location')),
            ],
            options={
                'db_table': 'needs',
                'verbose_name': 'Need',
                'verbose_name_plural': 'Needs',
            },
        ),
    ]
