# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0003_need'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Link'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Place'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='emergency',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name=b'Content'),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Place'),
        ),
        migrations.AlterField(
            model_name='helpline',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Title'),
        ),
        migrations.AlterField(
            model_name='need',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Contact'),
        ),
        migrations.AlterField(
            model_name='need',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Link'),
        ),
        migrations.AlterField(
            model_name='need',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Location'),
        ),
        migrations.AlterField(
            model_name='need',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='need',
            name='need',
            field=models.TextField(blank=True, null=True, verbose_name=b'Need'),
        ),
        migrations.AlterField(
            model_name='need',
            name='need_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Need id'),
        ),
        migrations.AlterField(
            model_name='need',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
        migrations.AlterField(
            model_name='post',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name=b'Link'),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Status'),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
    ]
