# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0004_auto_20170916_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='solved',
            field=models.BooleanField(default=False, verbose_name=b'Solved'),
        ),
    ]
