# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0004_auto_20170917_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Place'),
        ),
    ]
