# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callapp', '0005_need_solved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergency',
            options={'ordering': ['-id'], 'verbose_name': 'Emergency', 'verbose_name_plural': 'Emergencies'},
        ),
        migrations.AddField(
            model_name='emergency',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='need',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Created on'),
            preserve_default=False,
        ),
    ]
