# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 20:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128, unique=True, verbose_name=b'Name')),
                ('slug', models.SlugField(unique=True, verbose_name=b'Slug')),
            ],
            options={
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name=b'Name')),
                ('safe', models.BooleanField(db_index=True, default=False, verbose_name=b'Safe')),
                ('extra_info', models.TextField(verbose_name=b'Extra info')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.Area')),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
