# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='island',
            new_name='area',
        ),
    ]
