# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20170906_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True, verbose_name=b'Age'),
        ),
    ]
