# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_person_duplicate'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Contact'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Latitude', max_digits=9, null=True, verbose_name=b'Lat'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Longitude', max_digits=9, null=True, verbose_name=b'Long'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
    ]
