# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20170913_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Contact'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Latitude', max_digits=9, null=True, verbose_name=b'Lat'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Longitude', max_digits=9, null=True, verbose_name=b'Long'),
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='contact',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Contact'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Latitude', max_digits=9, null=True, verbose_name=b'Lat'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=6, help_text=b'Longitude', max_digits=9, null=True, verbose_name=b'Long'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='time',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Time'),
        ),
    ]
