# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_person_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='extra_info',
            field=models.TextField(blank=True, null=True, verbose_name=b'Extra info'),
        ),
    ]
