# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170913_1151'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name=b'Request'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='request',
            field=models.TextField(blank=True, null=True, verbose_name=b'Request'),
        ),
    ]
