# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_auto_20170907_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'District'),
        ),
    ]
