# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_person_district'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, help_text=b'Enter an email address if you want to receive a notification when someone is marked safe.', max_length=254, null=True, verbose_name=b'Notification email'),
        ),
    ]
