# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_auto_20170913_1207'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name=b'Place')),
                ('title', models.CharField(max_length=255, verbose_name=b'Title')),
                ('content', models.TextField(verbose_name=b'Content')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
            ],
            options={
                'db_table': 'help_lines',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name=b'Name')),
                ('link', models.URLField(verbose_name=b'Link')),
                ('time', models.CharField(max_length=75, verbose_name=b'Time')),
                ('status', models.CharField(max_length=255, verbose_name=b'Status')),
            ],
            options={
                'ordering': ['-id'],
                'db_table': 'posts',
            },
        ),
    ]
