# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 18:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_auto_20170907_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
        migrations.AddField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, help_text=b"The person's address", max_length=255, null=True, verbose_name=b'Address'),
        ),
        migrations.AddField(
            model_name='person',
            name='phonenumber',
            field=models.CharField(blank=True, help_text=b"The person's phone number", max_length=75, null=True, verbose_name=b'Phone number'),
        ),
        migrations.AddField(
            model_name='person',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name=b'Your Email'),
        ),
        migrations.AddField(
            model_name='person',
            name='requester_fb',
            field=models.URLField(blank=True, null=True, verbose_name=b'Your Facebook Profile'),
        ),
        migrations.AddField(
            model_name='person',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Your Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='requester_number',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name=b'Your Number'),
        ),
    ]
