# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 15:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_emergency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emergency',
        ),
        migrations.DeleteModel(
            name='HelpLine',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='long',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='long',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='request',
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='time',
        ),
        migrations.RemoveField(
            model_name='supplysharing',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='supplysharing',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='supplysharing',
            name='long',
        ),
        migrations.RemoveField(
            model_name='supplysharing',
            name='request',
        ),
        migrations.RemoveField(
            model_name='supplysharing',
            name='time',
        ),
    ]
