# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_auto_20170907_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='missing_since',
            field=models.CharField(default=None, verbose_name=b'Missing since', null=True, blank=True, max_length=255),
            preserve_default=False,
        ),
    ]
