# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 00:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_activity_activityreport'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'Activity', 'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='activityreport',
            options={'ordering': ['-created_on', '-resolved'], 'verbose_name': 'Activity Report', 'verbose_name_plural': 'Acivity Reports'},
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='district',
            field=models.CharField(db_index=True, help_text=b'I.e. Cupecoy, Cayhill, etc.,', max_length=255, verbose_name=b'District'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='reporter_name',
            field=models.CharField(max_length=255, verbose_name=b'Reporter name'),
        ),
        migrations.AlterField(
            model_name='activityreport',
            name='type',
            field=models.ForeignKey(help_text=b'Type of activity you would like to report.', on_delete=django.db.models.deletion.CASCADE, to='tracker.Activity'),
        ),
    ]
