# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_person_missing_since'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='person',
            name='missing_since',
            field=models.DateField(blank=True, null=True, verbose_name=b'Missing since'),
        ),
    ]
