# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20170907_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='missing_since',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Missing since'),
        ),
    ]
