# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0009_auto_20170916_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyrequest',
            name='district_admin',
            field=models.CharField(blank=True, db_index=True, help_text=b'District corrected by Admin', max_length=128, null=True, verbose_name=b'District'),
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='district_admin',
            field=models.CharField(blank=True, db_index=True, help_text=b'District corrected by Admin', max_length=128, null=True, verbose_name=b'District'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='district_admin',
            field=models.CharField(blank=True, db_index=True, help_text=b'District corrected by Admin', max_length=128, null=True, verbose_name=b'District'),
        ),
    ]
