# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_auto_20170907_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name=b'Created on'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='safe_email_sent',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Safe email sent'),
        ),
    ]
