# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-08 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_auto_20170908_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='marked_safe_on',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'Marked safe on'),
        ),
        migrations.AlterField(
            model_name='person',
            name='safe_email_sent',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name=b'Safe email sent'),
        ),
    ]
