# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_auto_20170908_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='safe_email_sent',
        ),
        migrations.AddField(
            model_name='person',
            name='safe_email_send',
            field=models.BooleanField(db_index=True, default=False, editable=False, verbose_name=b'Send Safe Email'),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name=b'Age'),
        ),
        migrations.AlterField(
            model_name='person',
            name='marked_safe_on',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name=b'Marked safe on'),
        ),
    ]
