# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 01:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_auto_20170909_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='notified',
            field=models.BooleanField(default=False, editable=False, verbose_name=b'Notified'),
        ),
    ]
