# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0014_person_notified'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=b'Emergency Contact Number'),
        ),
    ]
