# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 16:20
from __future__ import unicode_literals

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0015_auto_20170909_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name=b'image'),
        ),
    ]
