# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'images/', verbose_name=b'Image'),
        ),
    ]
