# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0018_auto_20170910_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SupplyRequest',
            new_name='SupplySharing',
        ),
        migrations.AlterModelTable(
            name='supplysharing',
            table='supply_sharing',
        ),
    ]
