# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 14:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_auto_20170910_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplysharing',
            options={'verbose_name': 'Supply Sharing', 'verbose_name_plural': 'Supply Sharing'},
        ),
        migrations.AddField(
            model_name='emergencyrequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Request resolved'),
        ),
    ]
