# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0020_auto_20170910_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='address',
            field=models.CharField(db_index=True, help_text=b'Street and number', max_length=255, verbose_name=b'Your Address'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='days_of_food',
            field=models.IntegerField(choices=[(0, b'None'), (1, b'Enough for 1 day'), (2, b'Enough for 2 days'), (3, b'Enough for more than 3 days')], default=3, help_text=b'How many days of food supplies do you have?', verbose_name=b'Days of food'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='days_of_water',
            field=models.IntegerField(choices=[(0, b'None'), (1, b'Enough for 1 day'), (2, b'Enough for 2 days'), (3, b'Enough for more than 3 days')], default=3, help_text=b'How many days of food supplies do you have?', verbose_name=b'Days of drinking water'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='has_injuries',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], db_index=True, default=0, verbose_name=b'Do you have a physical injury?'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='has_lod_situation',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], db_index=True, default=0, verbose_name=b'Are any of you in a life or death situation?'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='has_rain_shelter',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], db_index=True, default=0, verbose_name=b'Does your location have shelter from the rain?'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='has_shareable_supplies',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], db_index=True, default=0, verbose_name=b'Do you have supplies that you are willing share?'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='medical_supplies',
            field=models.TextField(blank=True, help_text=b"If you answered 'Yes' to medical supplies, please specify the supplies you need.", null=True, verbose_name=b'Immediate medical supplies'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='request',
            field=models.TextField(verbose_name=b'In short, can you describe your emergency and/or request'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='requires_medical_supplies',
            field=models.IntegerField(choices=[(0, b'No'), (1, b'Yes')], default=0, verbose_name=b'Does anyone need immediate medical supplies?'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='shareable_supplies',
            field=models.TextField(blank=True, null=True, verbose_name=b"Please specify the supplies you're willing to share"),
        ),
        migrations.AlterField(
            model_name='supplysharing',
            name='address',
            field=models.CharField(db_index=True, help_text=b'Street and number', max_length=255, verbose_name=b'Your Address'),
        ),
        migrations.AlterField(
            model_name='supplysharing',
            name='shareable_supplies',
            field=models.TextField(blank=True, help_text=b'Specify the type of supplies and their quantities. Every item that you have to spare can make a difference in someone elses life.', null=True, verbose_name=b'Shareable Supplies'),
        ),
    ]
