# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_auto_20170910_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplysharing',
            name='additional_persons',
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='pickup_instructions',
            field=models.TextField(blank=True, help_text=b'I.e. The front door is obstructed, please use the back door.', null=True, verbose_name=b'Pickup Instructions'),
        ),
    ]
