# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 00:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0022_auto_20170910_2248'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emergencyrequest',
            options={'ordering': ['urgency_ranking'], 'verbose_name': 'Emergency Request', 'verbose_name_plural': 'Emergency Requests'},
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='has_shareable_supplies',
        ),
        migrations.RemoveField(
            model_name='emergencyrequest',
            name='shareable_supplies',
        ),
    ]
