# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 01:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0023_auto_20170911_0017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='emergencyrequest',
            unique_together=set([('address', 'district', 'contact_numbers')]),
        ),
    ]
