# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-11 14:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0024_auto_20170911_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='marked_safe_by',
            field=models.CharField(blank=True, max_length=126, null=True, verbose_name=b'Marked safe by'),
        ),
    ]
