# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0025_person_marked_safe_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=128, verbose_name=b'Full name')),
                ('address', models.CharField(db_index=True, help_text=b'Street and number', max_length=255, verbose_name=b'Your Address')),
                ('district', models.CharField(db_index=True, help_text=b'I.e. Cupecoy, Cayhill, etc.,', max_length=128, verbose_name=b'District')),
                ('contact_numbers', models.CharField(blank=True, max_length=128, null=True, verbose_name=b'Contact Numbers')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name=b'Created on')),
                ('needed_supplies', models.TextField(blank=True, help_text=b'Specify the type of supplies you need', null=True, verbose_name=b'Needed supplies')),
                ('dropoff_instructions', models.TextField(blank=True, help_text=b'I.e. The front door is obstructed, please use the back door.', null=True, verbose_name=b'Dropoff Instructions')),
            ],
            options={
                'db_table': 'supply_requests',
                'verbose_name': 'Supply Request',
                'verbose_name_plural': 'Supply Requests',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='marked_safe_by',
            field=models.CharField(blank=True, help_text=b'Name of the person checking this box', max_length=126, null=True, verbose_name=b'Marked safe by'),
        ),
    ]
