# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0026_auto_20170912_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyrequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Request Resolved'),
        ),
        migrations.AddField(
            model_name='supplysharing',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Request Resolved'),
        ),
        migrations.AlterField(
            model_name='emergencyrequest',
            name='resolved',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Request Resolved'),
        ),
    ]
