# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0027_auto_20170912_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyrequest',
            name='urgency_ranking',
            field=models.IntegerField(db_index=True, default=5, verbose_name=b'Urgency ranking'),
        ),
    ]
