# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0029_auto_20170912_1255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name=b'Item name')),
            ],
            options={
                'db_table': 'supplies',
            },
        ),
        migrations.RemoveField(
            model_name='supplyrequest',
            name='needed_supplies',
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='supplies',
            field=models.ManyToManyField(db_index=True, help_text=b'Specify the type of supplies you need', to='tracker.Supply'),
        ),
    ]
