# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0030_auto_20170912_1751'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'verbose_name': 'Supply', 'verbose_name_plural': 'Supplies'},
        ),
        migrations.AddField(
            model_name='supplyrequest',
            name='quantity',
            field=models.IntegerField(default=1, help_text=b'Indicate how many people these supplies need to cover', verbose_name=b'Amount of people'),
        ),
        migrations.AlterField(
            model_name='supplyrequest',
            name='supplies',
            field=models.ManyToManyField(db_index=True, help_text=b"Select which supplies you're in need of", to='tracker.Supply'),
        ),
    ]
