# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0031_auto_20170912_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplyrequest',
            options={'ordering': ['created_on', '-resolved'], 'verbose_name': 'Supply Request', 'verbose_name_plural': 'Supply Requests'},
        ),
        migrations.AlterModelOptions(
            name='supplysharing',
            options={'ordering': ['created_on', '-resolved'], 'verbose_name': 'Supply Sharing', 'verbose_name_plural': 'Supply Sharing'},
        ),
        migrations.AddField(
            model_name='person',
            name='duplicate',
            field=models.BooleanField(db_index=True, default=False, verbose_name=b'Duplicate'),
        ),
    ]
